### ISSUE TITLE
Add record player variation with standard sound

### ISSUE THREAD

**Issue by mica-alex** [Mica-Technologies/minecraft-city-super-mod#1]

**Comment by AngelWingsPanda** [comment]
Now that I’m adding custom music (the Alto Original Soundtrack) made by myself into the game, we might try to replace some of the record music in game with a few various tracks, of course made by me and a few that we’ve found that would be royalty free to avoid any copyright issues. The record player will mainly be a cruddy record player that it always has been since it’s just a useless and silly gag item that I’ve had to add to the mod just for fun and giggles. I might come back to this eventually but for now this issue is now closed.
