### ISSUE TITLE
Add abstract renderer class

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#100]
We need to have a better render class that is slightly based on the Forge blockstate renderer except abstract to be used and shared anywhere with other abstract classes across the mod. This class will render JSON and OBJ models along with any other formats we might come across in the near future.

**Comment by AngelWingsPanda** [comment]
Happy 100th issue this now seems to be! This certainly won't be the last for sure!

**Comment by mica-alex** [comment]
This issue can be closed. Forge rendering does not work like this, and there is no need for us to implement any rendering functionality of our own across the mod.

Forge handles blockstate based rendering entirely on its own in a static system which batches render calls for identical blockstates. Custom rendering pipelines do not receive batch processing, and therefore, are by design, less efficient than the static rendering provided natively by Forge.

Custom render functionality can be required under circumstances where too many block states would exist for the game to handle properly, for example the upcoming traffic signal system. Outside of these circumstances though, there is no benefit or gain to implementing custom rendering, as it has the potential to hurt performance by increasing GPU usage.

_To explain Forge's static/blockstate rendering vs. custom rendering, here is a comparison:
- You have a world with hundreds of stop signs, and there are currently 25 visible on the screen...
- Using Forge static rendering, each of the 25 stop signs being rendered on the screen are batched together and rendered in one single operation (and one single OpenGL state change)
- Using custom rendering, each of the 25 stop signs being rendered on the screen are called individually, resulting in 25 separate render operations (and 25 OpenGL state changes)_

**Comment by mica-alex** [comment]
Specifically, regarding alternative model formats such as OBJ models, the CSM mod already enabled the Forge OBJ model loader.

Support for alternate model formats is something handled by Forge itself, and although CSM does need to tell Forge to enable the alternate model format, this is something that was already enabled in CSM many releases ago. 

To see an example of an OBJ model being used in CSM currently, take a look at this commit: https://github.com/Mica-Technologies/minecraft-city-super-mod/commit/4978b7c08c9b9f554d54ca8256f7ed3d35888d64
- In this commit, the traffic signal controller block is switched to an OBJ/MTL model, and you can see the blockstate file to make it work. 
- The only real steps required to make OBJ models work is to put the right model name in the blockstate file, and to be sure the texture names in the .MTL file match the Minecraft format. You can see this in the commit as well.
