### ISSUE TITLE
Add black emergency lighting variant

### ISSUE THREAD

**Issue by mica-alex** [Mica-Technologies/minecraft-city-super-mod#4]

**Comment by mica-alex** [comment]
@AngelWingsPanda Do you remember what this was about? Was it different color variants or something else?

Would you be able to step in and make this addition?

**Comment by AngelWingsPanda** [comment]
> @AngelWingsPanda Do you remember what this was about? Was it different color variants or something else?
> 
> Would you be able to step in and make this addition?

This was opened a while back by you @mica-alex to add additional colors to the emergency lights. I’m not sure what colors you were originally requesting earlier, but I guess we can do colors the same way as the colored metals that will be coming back to the mod, thus adding it to the auto generated code for all the metal blocks since most emergency lights at Alto Life Safety will be vastly improved. All of the new variants we plan on adding will mostly be die cast instead of cheap polycarbonate now (with an exception to the already existing polycarbonate ones already in the mod). This will mostly continue onwards in a new issue that will be opened up anyways since a new abstract class will have to be made just for the new metal ones.

As for now, I renamed this issue as requested to mention that a black polycarbonate variant still needs to be done. We already have that texture already in the mod, but the code for that block still hasn’t been added in yet.

And yes, I will be willing to help you out on this matter, since it shouldn’t be too hard to do anyways.
