### ISSUE TITLE
Fix and clean up textures

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#51]
This still needs to be done as I keep on forgetting to do this.

**Comment by mica-alex** [comment]
@AngelWingsPanda Are you able to look at doing this in the near future? Organizing/cleaning the resources folders (namely the textures and sounds) will be a top priority soon, because it will make the mod much more lightweight and smaller in size.
<br/>
### Note

**Do not change the structure of models**. I plan to separately address the model resources further down the road, as this will require more in-depth changes that will affect core mod functionality.

**Comment by AngelWingsPanda** [comment]
> @AngelWingsPanda Are you able to look at doing this in the near future? Organizing/cleaning the resources folders (namely the textures and sounds) will be a top priority soon, because it will make the mod much more lightweight and smaller in size.
> 
> ### Note
> **Do not change the structure of models**. I plan to separately address the model resources further down the road, as this will require more in-depth changes that will affect core mod functionality.

Yep that is my ultimate goal but I still have to go through everything first and see what we have that is already being used by the mod or not.

**Comment by AngelWingsPanda** [comment]
Texture cleanup is mostly complete by now. All that is left is to clean up the sounds.

**Comment by mica-alex** [comment]
> > Texture cleanup is mostly complete by now. All that is left is to clean up the sounds.
> 
> Yep -- this has all looked really good. I saw the remaining parts come through the PR last night/this morning.
> 
> Do be careful in the future not to commit any unintended deletions though, as I did need to fixup the commit just a tad to undo the removal of all the generated bounding box files.

Closing issue now as this has been addressed mainly.
