### ISSUE TITLE
Clean up sounds

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#52]
This just like the texture cleanup also needs to be done.

**Comment by mica-alex** [comment]
![image](https://github.com/Mica-Technologies/minecraft-city-super-mod/assets/83238954/f3e7200b-4a3d-4d76-bef8-1a0f6c71e6ad)

All sounds that are not active in the mod should be moved to this location, so they do not clutter the active mod resources folder(s)

**Comment by mica-alex** [comment]
@AngelWingsPanda Are you able to look at doing this in the near future? Organizing/cleaning the resources folders (namely the textures and sounds) will be a top priority soon, because it will make the mod much more lightweight and smaller in size.
<br/>
### Note

**Do not change the structure of models**. I plan to separately address the model resources further down the road, as this will require more in-depth changes that will affect core mod functionality.
