### ISSUE TITLE
Fix broken code on fire alarms

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#53]
All fire alarm abstract code appears to not be working properly, with the exception of the alarm linking that only works currently. Activating any alarms does nothing, along with alarm status messages not being displayed.

**Comment by mica-alex** [comment]
There is no issue with abstract code. This issue is with regards to the alarm panel not operating as expected.

**Comment by mica-alex** [comment]
The alarm panel has been migrated multiple times across various TE frameworks in CSM. Unlike the signal controller which was recently rewritten, the alarm panel block contains older and questionable code. 

The end result for resolving this bug seems to lean towards rewriting portions of the alarm panel.

**Comment by AngelWingsPanda** [comment]
A complete total rewrite of the entire fire alarm code will need to be redone to fix issues #53 #8

**Comment by AngelWingsPanda** [comment]
Opening this as a new issue now.
