### ISSUE TITLE
Create lang file sort/translate tool

### ISSUE THREAD

**Issue by mica-alex** [Mica-Technologies/minecraft-city-super-mod#62]
Create a tool to automatically sort lang file entries alphabetically, as well as possible automatic translation using Google Translate or AI API.

**Comment by AngelWingsPanda** [comment]
> Create a tool to automatically sort lang file entries alphabetically, as well as possible automatic translation using Google Translate or AI API.

I just know that this will be a TON of work for us to do, but I think it would be possible with Google Translate. As for an AI like ChatGPT to do it for us, you’re looking at a bunch of rate limiting and character limits for what we can be able to translate, all that we still need to look into even more ourselves. For simplicity’s sake, we should only focus on just a few languages that most people would likely be using the mod in, mainly with Spanish (I’ll leave that to you since you know quite a bit) and French.

**Comment by mica-alex** [comment]
Yep — the tool is rather simple. The concerns really rest with the translation portion. I am not confident enough in anything besides English, therefore any translation is really reliant upon the availability of a translation API.

That being said though, one thing to consider is that once the existing stuff is organized and translated to a few languages we decide to support, then anything added in the future it would be expected that you or I or whoever the developer is would include all relevant translations. Whether one decides to use AI or google translate is up to them.

**Comment by mica-alex** [comment]
The sorting piece of the tool is rather simple though and can be accomplished simply by parsing the current lang file in to a list, sorting the list, then outputting it back to the file in the correct format. 

The list will have the formatting already, so there isn’t much required on that front too.
